#!/usr/bin/ruby
require 'rubygems'
require 'cgi'
require 'json'
require 'open-uri'
require 'httparty'
require 'nokogiri'
require 'hpricot'
require 'plist'
require 'trailers/httparty_icebox'
require 'trailers/trailer'
require 'trailers/trailer_source'
require 'trailers/apple_trailer_source'
require 'trailers/itms_trailer_source'
require 'trailers/smart_trailer_source'
require 'trailers/movie'
